services:
  mongo:
    image: mongo:7
    container_name: shipnow-mongo
    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10


  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: shipnow-api

    restart: unless-stopped

    depends_on:
      mongo:
        condition: service_healthy

    environment:
      PORT: 8080
      NODE_ENV: production
      LOG_LEVEL: info
      MONGODB_URI: mongodb://mongo:27017/shipnow-api

    ports:
      - "8080:8080"

    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs


volumes:
  mongo_data: